genome:
    .../assembly.fa

hg38:
    .../GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

regions:
	sda: .../coverage/chm13.collapses.bed

reads:
    pacbio: .../reads.pacbio.fastq
    nanopore: .../reads.nanopore.fastq

#Paths to tools (minimap2, samtools and bedtools are assumed to be in PATH)
tools:
    paftest: .../WHdenovo/paftest
    bandage: .../Bandage
    mc-mpc: .../mc-mpc
    graphaligner: .../GraphAligner
    quast: .../quast.py
    svim-asm: .../svim-asm
    racon: .../racon

bacs:
    fasta: .../bacs.fa
