#Add paths to the input reads below:
#   Firstly, add the name of each sample (e.g. r1)
#       Then, for each sample add the paths to the FASTA files of PacBio HiFi and Ultralong Nanopore reads
reads:
    r1:
        pacbio: pacbio.r1.fasta
        nanopore: nanopore.r1.fasta

#Add the path to the reference genome below:
reference:
    GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

#Optionally customize the pruning parameters below:
params:
    tip_max_size: 5
    bubble_min_length: 5000
    degree_max_size: 2
