genome:
    .../assembly.fa

hg38:
    .../GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

regions:
	sda: .../coverage/chm13.collapses.bed

reads:
    pacbio: .../reads.pacbio.fastq
    nanopore: .../reads.nanopore.fastq

bacs:
    fasta: .../bacs.fa
